# Generated by Django 6.0 on 2026-05-30 16:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(blank=True, help_text='Format: XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, help_text='The company this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='medicoes.company')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='medicoes.company')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MeasurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='measurements/%Y/%m/%d/')),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=list, help_text='Stores raw JSON specs of each contour: length, width, grayscale, and rgb values.')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Measurement Record',
                'verbose_name_plural': 'Measurement Records',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_index', models.PositiveIntegerField(help_text='Visual ordering or detection sequence index')),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grayscale_value', models.PositiveSmallIntegerField(help_text='Grayscale color index (0-255)')),
                ('r_value', models.PositiveSmallIntegerField(help_text='Red value (0-255)')),
                ('g_value', models.PositiveSmallIntegerField(help_text='Green value (0-255)')),
                ('b_value', models.PositiveSmallIntegerField(help_text='Blue value (0-255)')),
                ('measurement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medicoes.measurementrecord')),
            ],
            options={
                'verbose_name': 'Measurement Item',
                'verbose_name_plural': 'Measurement Items',
                'ordering': ['measurement_record', 'item_index'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='E.g., 48019', max_length=50, unique=True)),
                ('name', models.CharField(help_text='E.g., ESTRELA CREAM CRACKER 20X400', max_length=255)),
                ('target_width_cm', models.DecimalField(decimal_places=2, help_text='Standard expected width in cm', max_digits=5)),
                ('target_length_cm', models.DecimalField(decimal_places=2, help_text='Standard expected length/height in cm', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='medicoes.productionline')),
            ],
            options={
                'verbose_name': 'Product SKU',
                'verbose_name_plural': 'Product SKUs',
            },
        ),
        migrations.AddField(
            model_name='measurementrecord',
            name='product_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='medicoes.productsku'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='medicoes.department')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productionline',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='medicoes.sector'),
        ),
        migrations.AlterUniqueTogether(
            name='productionline',
            unique_together={('sector', 'name')},
        ),
    ]
