# Generated by Django 6.0 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementrecord',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='original_inspections/%Y/%m/%d/'),
        ),
    ]
