# Generated by Django 6.0 on 2026-05-31 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0002_measurementrecord_original_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_format', models.CharField(choices=[('RECTANGULAR', 'Rectangular / Square'), ('ROUND', 'Round / Circular')], default='RECTANGULAR', help_text='The geometric category of the product. Circular items trigger specific radial metrics.', max_length=20)),
                ('canny_threshold_low', models.PositiveSmallIntegerField(default=30, help_text='Lower hysteresis threshold for Canny edge detection. Lower values capture weaker edges.')),
                ('canny_threshold_high', models.PositiveSmallIntegerField(default=80, help_text='Upper hysteresis threshold for Canny edge detection. Helps map strong object borders.')),
                ('blur_kernel_size', models.PositiveSmallIntegerField(default=5, help_text='Gaussian blur filter size in pixels (must be odd, e.g. 3, 5, 7) to mitigate high-frequency capture noise.')),
                ('erosion_amount', models.PositiveSmallIntegerField(default=1, help_text='Number of 3x3 morphology erosion loops applied to contract swollen product borders and counteract blooming.')),
                ('resolution_width', models.PositiveIntegerField(default=1280, help_text='Target video feed resolution width in pixels (e.g. 1280 for 720p capture).')),
                ('resolution_height', models.PositiveIntegerField(default=720, help_text='Target video feed resolution height in pixels (e.g. 720 for 720p capture).')),
                ('brightness_target', models.PositiveSmallIntegerField(default=128, help_text='Ideal average grayscale target value for backlight exposure normalization.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='medicoes.productsku')),
            ],
            options={
                'verbose_name': 'SKU Configuration',
                'verbose_name_plural': 'SKU Configurations',
            },
        ),
    ]
