# Generated by Django 6.0 on 2026-05-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0003_skuconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuconfiguration',
            name='length_offset_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed calibration offset in millimeters added to raw length. E.g., 2.00 adds 2.0mm.', max_digits=5),
        ),
        migrations.AddField(
            model_name='skuconfiguration',
            name='width_offset_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed calibration offset in millimeters added to raw width. E.g., -1.50 subtracts 1.5mm.', max_digits=5),
        ),
    ]
