# Generated by Django 6.0 on 2026-06-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0004_skuconfiguration_length_offset_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuconfiguration',
            name='gray_target_value',
            field=models.PositiveSmallIntegerField(default=128, help_text='Reference average grayscale [0-255].'),
        ),
        migrations.AddField(
            model_name='skuconfiguration',
            name='gray_tolerance_range',
            field=models.PositiveSmallIntegerField(default=20, help_text='Acceptable deviation (+/-).'),
        ),
        migrations.AddField(
            model_name='skuconfiguration',
            name='rgb_spectrum_variance',
            field=models.PositiveSmallIntegerField(default=30, help_text='Acceptable spectrum variance tolerance boundary (+/-).'),
        ),
        migrations.AddField(
            model_name='skuconfiguration',
            name='rgb_target_b',
            field=models.PositiveSmallIntegerField(default=128, help_text='Reference average RGB Blue component [0-255].'),
        ),
        migrations.AddField(
            model_name='skuconfiguration',
            name='rgb_target_g',
            field=models.PositiveSmallIntegerField(default=128, help_text='Reference average RGB Green component [0-255].'),
        ),
        migrations.AddField(
            model_name='skuconfiguration',
            name='rgb_target_r',
            field=models.PositiveSmallIntegerField(default=128, help_text='Reference average RGB Red component [0-255].'),
        ),
    ]
