# Generated by Django 6.0 on 2026-06-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0005_skuconfiguration_gray_target_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='measurementitem',
            options={'ordering': ['measurement_record', 'item_index'], 'verbose_name': 'Item de Medição', 'verbose_name_plural': 'Itens de Medição'},
        ),
        migrations.AlterModelOptions(
            name='measurementrecord',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Registro de Medição', 'verbose_name_plural': 'Registros de Medições'},
        ),
        migrations.AlterModelOptions(
            name='productionline',
            options={'verbose_name': 'Linha de Produção', 'verbose_name_plural': 'Linhas de Produção'},
        ),
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name': 'SKU de Produto', 'verbose_name_plural': 'SKUs de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterModelOptions(
            name='skuconfiguration',
            options={'verbose_name': 'Configuração do SKU', 'verbose_name_plural': 'Configurações dos SKUs'},
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Formato: XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='A empresa à qual este usuário pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='medicoes.company'),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='b_value',
            field=models.PositiveSmallIntegerField(help_text='Valor do canal Azul (Blue) (0-255)'),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='g_value',
            field=models.PositiveSmallIntegerField(help_text='Valor do canal Verde (Green) (0-255)'),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='grayscale_value',
            field=models.PositiveSmallIntegerField(help_text='Índice de cor em escala de cinza (0-255)'),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='item_index',
            field=models.PositiveIntegerField(help_text='Índice de ordenação visual ou sequência de detecção'),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='r_value',
            field=models.PositiveSmallIntegerField(help_text='Valor do canal Vermelho (Red) (0-255)'),
        ),
        migrations.AlterField(
            model_name='measurementrecord',
            name='raw_data',
            field=models.JSONField(blank=True, default=list, help_text='Armazena especificações JSON brutas de cada contorno: comprimento, largura, escala de cinza e valores RGB.'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='code',
            field=models.CharField(help_text='Ex: 48019', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='name',
            field=models.CharField(help_text='Ex: ESTRELA CREAM CRACKER 20X400', max_length=255),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='target_length_cm',
            field=models.DecimalField(decimal_places=2, help_text='Comprimento/altura padrão esperado em cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='target_width_cm',
            field=models.DecimalField(decimal_places=2, help_text='Largura padrão esperada em cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='blur_kernel_size',
            field=models.PositiveSmallIntegerField(default=5, help_text='Tamanho do filtro de desfoque gaussiano em pixels (deve ser ímpar, ex: 3, 5, 7) para mitigar ruídos de captura de alta frequência.'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='brightness_target',
            field=models.PositiveSmallIntegerField(default=128, help_text='Valor alvo ideal da média de escala de cinza para normalização de exposição do backlight.'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='canny_threshold_high',
            field=models.PositiveSmallIntegerField(default=80, help_text='Limite de histerese superior para detecção de bordas Canny. Ajuda a mapear bordas fortes de objetos.'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='canny_threshold_low',
            field=models.PositiveSmallIntegerField(default=30, help_text='Limite de histerese inferior para detecção de bordas Canny. Valores mais baixos capturam bordas mais fracas.'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='erosion_amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de repetições de erosão morfológica 3x3 aplicadas para contrair bordas expandidas do produto e neutralizar o blooming.'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='gray_target_value',
            field=models.PositiveSmallIntegerField(default=128, help_text='Média de escala de cinza de referência [0-255].'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='gray_tolerance_range',
            field=models.PositiveSmallIntegerField(default=20, help_text='Desvio aceitável (+/-).'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='length_offset_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Offset de calibração fixo em milímetros adicionado ao comprimento bruto. Ex: 2.00 adiciona 2.0mm.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='object_format',
            field=models.CharField(choices=[('RECTANGULAR', 'Retangular / Quadrado'), ('ROUND', 'Redondo / Circular')], default='RECTANGULAR', help_text='A categoria geométrica do produto. Itens circulares ativam métricas radiais específicas.', max_length=20),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='resolution_height',
            field=models.PositiveIntegerField(default=720, help_text='Altura de resolução do feed de vídeo alvo em pixels (ex: 720 para captura 720p).'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='resolution_width',
            field=models.PositiveIntegerField(default=1280, help_text='Largura de resolução do feed de vídeo alvo em pixels (ex: 1280 para captura 720p).'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='rgb_spectrum_variance',
            field=models.PositiveSmallIntegerField(default=30, help_text='Limite aceitável de tolerância de variância de espectro (+/-).'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='rgb_target_b',
            field=models.PositiveSmallIntegerField(default=128, help_text='Componente Azul (Blue) RGB médio de referência [0-255].'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='rgb_target_g',
            field=models.PositiveSmallIntegerField(default=128, help_text='Componente Verde (Green) RGB médio de referência [0-255].'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='rgb_target_r',
            field=models.PositiveSmallIntegerField(default=128, help_text='Componente Vermelho (Red) RGB médio de referência [0-255].'),
        ),
        migrations.AlterField(
            model_name='skuconfiguration',
            name='width_offset_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Offset de calibração fixo em milímetros adicionado à largura bruta. Ex: -1.50 subtrai 1.5mm.', max_digits=5),
        ),
    ]
