version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - ./data:/app/data
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=medidor_project.settings
